-- Baseline schema, reproducing what Hibernate's ddl-auto generated up to this point.
-- From here on, schema changes are versioned Flyway migrations instead of ddl-auto.

CREATE TABLE tb_user (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50)  NOT NULL,
    username VARCHAR(20)  NOT NULL,
    email    VARCHAR(120) NOT NULL,
    password VARCHAR(120) NOT NULL,
    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT uk_user_email UNIQUE (email)
);

CREATE TABLE tb_folder (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(60)  NOT NULL,
    description VARCHAR(160),
    color       VARCHAR(20),
    created_at  TIMESTAMP,
    CONSTRAINT uk_folder_name UNIQUE (name)
);

CREATE TABLE tb_tag (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(40) NOT NULL,
    color VARCHAR(20),
    CONSTRAINT uk_tag_name UNIQUE (name)
);

CREATE TABLE tb_post (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(120) NOT NULL,
    url            VARCHAR(500) NOT NULL,
    description    VARCHAR(500),
    source         VARCHAR(20)  NOT NULL,
    thumbnail_url  VARCHAR(500),
    is_favorite    BOOLEAN      NOT NULL,
    folder_id      BIGINT,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT fk_post_folder FOREIGN KEY (folder_id) REFERENCES tb_folder (id)
);

CREATE TABLE tb_post_tag (
    post_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,
    CONSTRAINT pk_post_tag PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_post_tag_post FOREIGN KEY (post_id) REFERENCES tb_post (id),
    CONSTRAINT fk_post_tag_tag FOREIGN KEY (tag_id) REFERENCES tb_tag (id)
);
